import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://demoqa.com/")
driver.execute_script("window.scrollBy(0, 500);")
time.sleep(2)
elements = driver.find_element_by_xpath("//h5[text()='Elements']")
elements.click()
time.sleep(2)
check_box = driver.find_element_by_xpath("//span[text()='Check Box']")
check_box.click()
home = driver.find_element_by_class_name("rct-title")
home.click()
time.sleep(1)
radio_button = driver.find_element_by_xpath("//span[text()='Radio Button']")
radio_button.click()
impressive = driver.find_element_by_xpath("//label[contains(@for,'impressiveRadio')]")
impressive.click()
time.sleep(1)
yes = driver.find_element_by_xpath("//label[contains(@for,'yesRadio')]")
yes.click()
driver.quit()